import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:project_taxi_driver_app/data/models/driver_model.dart';
import 'package:project_taxi_driver_app/domain/entities/driver.dart';
import 'package:project_taxi_driver_app/domain/repositories/driver_repository.dart';

class DriverRepositoryImpl implements DriverRepository {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final FirebaseAuth _auth = FirebaseAuth.instance;
  final String _collection = 'drivers'; // Changed from 'fleet_drivers'

  @override
  Future<List<Driver>> getDrivers() async {
    try {
      final user = _auth.currentUser;
      if (user == null) return [];

      // Query drivers belonging to this fleet operator
      // Assuming the current user IS the fleet operator
      final snapshot = await _firestore
          .collection(_collection)
          .where('fleetOperatorId', isEqualTo: user.uid)
          .get();

      return snapshot.docs.map((doc) => DriverModel.fromSnapshot(doc)).toList();
    } catch (e) {
      throw Exception("Error fetching drivers: $e");
    }
  }

  @override
  Future<void> addDriver(Driver driver) async {
    try {
      final model = DriverModel(
        id: '', // Generated by Firestore
        name: driver.name,
        email: driver.email,
        phoneNumber: driver.phoneNumber,
        licenseNumber: driver.licenseNumber,
        status: driver.status,
        currentVehicleId: driver.currentVehicleId,
        profileImageUrl: driver.profileImageUrl,
        joinedDate: driver.joinedDate,
        rating: driver.rating,
      );
      await _firestore.collection(_collection).add(model.toJson());
    } catch (e) {
      throw Exception("Error adding driver: $e");
    }
  }

  @override
  Future<void> updateDriver(Driver driver) async {
    try {
      final model = DriverModel(
        id: driver.id,
        name: driver.name,
        email: driver.email,
        phoneNumber: driver.phoneNumber,
        licenseNumber: driver.licenseNumber,
        status: driver.status,
        currentVehicleId: driver.currentVehicleId,
        profileImageUrl: driver.profileImageUrl,
        joinedDate: driver.joinedDate,
        rating: driver.rating,
      );
      await _firestore
          .collection(_collection)
          .doc(driver.id)
          .update(model.toJson());
    } catch (e) {
      throw Exception("Error updating driver: $e");
    }
  }

  @override
  Future<void> deleteDriver(String id) async {
    try {
      final docRef = _firestore.collection(_collection).doc(id);
      final docSnapshot = await docRef.get();

      if (docSnapshot.exists) {
        final data = docSnapshot.data() as Map<String, dynamic>;
        final String? vehicleId =
            data['vehicleId'] ?? data['currentVehicleId']; // Check both keys

        if (vehicleId != null && vehicleId.isNotEmpty) {
          await _firestore.collection('vehicles').doc(vehicleId).update({
            'assignedDriverId': FieldValue.delete(), // Or null
            'status': 'Active', // Make available again
          });
        }
      }

      await docRef.delete();
    } catch (e) {
      throw Exception("Error deleting driver: $e");
    }
  }

  @override
  Future<Driver?> getDriverById(String id) async {
    try {
      final doc = await _firestore.collection(_collection).doc(id).get();
      if (doc.exists) {
        return DriverModel.fromSnapshot(doc);
      }
      return null;
    } catch (e) {
      throw Exception("Error getting driver: $e");
    }
  }
}
