import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:project_taxi_driver_app/data/models/vehicle_model.dart';
import 'package:project_taxi_driver_app/domain/entities/vehicle.dart';
import 'package:project_taxi_driver_app/domain/repositories/vehicle_repository.dart';

class VehicleRepositoryImpl implements VehicleRepository {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final String _collection = 'vehicles';

  @override
  Future<List<Vehicle>> getVehicles(String userId) async {
    try {
      final snapshot = await _firestore
          .collection(_collection)
          .where('ownerId', isEqualTo: userId)
          .get();
      return snapshot.docs
          .map((doc) => VehicleModel.fromSnapshot(doc))
          .toList();
    } catch (e) {
      throw Exception("Error fetching vehicles: $e");
    }
  }

  @override
  Future<void> addVehicle(Vehicle vehicle) async {
    try {
      final model = VehicleModel(
        id: '', // ID generated by Firestore
        plateNumber: vehicle.plateNumber,
        model: vehicle.model,
        type: vehicle.type,
        status: vehicle.status,
        assignedDriverId: vehicle.assignedDriverId,
        imageUrl: vehicle.imageUrl,
        fuelLevel: vehicle.fuelLevel,
        lastMaintenanceDate: vehicle.lastMaintenanceDate,
      );
      await _firestore.collection(_collection).add(model.toJson());
    } catch (e) {
      throw Exception("Error adding vehicle: $e");
    }
  }

  @override
  Future<void> updateVehicle(Vehicle vehicle) async {
    try {
      final model = VehicleModel(
        id: vehicle.id,
        plateNumber: vehicle.plateNumber,
        model: vehicle.model,
        type: vehicle.type,
        status: vehicle.status,
        assignedDriverId: vehicle.assignedDriverId,
        imageUrl: vehicle.imageUrl,
        fuelLevel: vehicle.fuelLevel,
        lastMaintenanceDate: vehicle.lastMaintenanceDate,
      );
      await _firestore
          .collection(_collection)
          .doc(vehicle.id)
          .update(model.toJson());
    } catch (e) {
      throw Exception("Error updating vehicle: $e");
    }
  }

  @override
  Future<void> deleteVehicle(String id) async {
    try {
      final docRef = _firestore.collection(_collection).doc(id);
      final docSnapshot = await docRef.get();

      if (docSnapshot.exists) {
        final data = docSnapshot.data() as Map<String, dynamic>;
        final String? driverId = data['assignedDriverId'];

        if (driverId != null && driverId.isNotEmpty) {
          await _firestore.collection('drivers').doc(driverId).update({
            'vehicleId': FieldValue.delete(),
            'currentVehicleId': FieldValue.delete(),
          });
        }
      }

      await docRef.delete();
    } catch (e) {
      throw Exception("Error deleting vehicle: $e");
    }
  }

  @override
  Future<Vehicle?> getVehicleById(String id) async {
    try {
      final doc = await _firestore.collection(_collection).doc(id).get();
      if (doc.exists) {
        return VehicleModel.fromSnapshot(doc);
      }
      return null;
    } catch (e) {
      throw Exception("Error getting vehicle: $e");
    }
  }
}
